#!perl

package httpthis;

use strict;
use warnings;
use App::HTTPThis;

# VERSION

App::HTTPThis->new->run;

1;
# ABSTRACT: export the current directory over HTTP
# PODNAME:

=head1 SYNOPSIS

 % httpthis

For more options, see L<http_this> (use C<man http_this> or C<http_this
--help>).


=head1 DESCRIPTION

This is an alias for http_this in the App-HTTPThis CPAN distribution.


=head1 SEE ALSO

L<http_this>

=cut
